"""changes

Revision ID: 0972a41c9fb0
Revises: cbbd30b1eb1b
Create Date: 2019-04-04 19:23:20.466168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0972a41c9fb0'
down_revision = 'cbbd30b1eb1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('process_doc', sa.Column('idkujk', sa.Integer(), autoincrement=True, nullable=False))
    op.drop_column('process_doc', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('process_doc', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('process_doc', 'idkujk')
    # ### end Alembic commands ###
