"""new structure rename

Revision ID: 37c3dd1eb90d
Revises: eb953db824d4
Create Date: 2019-04-04 18:11:49.350237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37c3dd1eb90d'
down_revision = 'eb953db824d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('split_question',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('nodeId', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['nodeId'], ['node.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('splitquestion')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('splitquestion',
    sa.Column('id', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('nodeId', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['nodeId'], ['node.id'], name='splitquestion_nodeId_fkey'),
    sa.PrimaryKeyConstraint('id', name='splitquestion_pkey')
    )
    op.drop_table('split_question')
    # ### end Alembic commands ###
