"""return to original

Revision ID: 4a243c196e6f
Revises: 8f4123253988
Create Date: 2019-04-04 15:28:09.315994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a243c196e6f'
down_revision = '8f4123253988'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('process', sa.Column('importDate', sa.Integer(), nullable=True))
    op.drop_column('process', 'Date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('process', sa.Column('Date', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('process', 'importDate')
    # ### end Alembic commands ###
