"""new structure noExec entfernt & DeleteCascade dazu

Revision ID: 5d17b251e57e
Revises: 37c3dd1eb90d
Create Date: 2019-04-04 18:33:31.810749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d17b251e57e'
down_revision = '37c3dd1eb90d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('button_name_nodeId_fkey', 'button_name', type_='foreignkey')
    op.create_foreign_key(None, 'button_name', 'node', ['nodeId'], ['id'], ondelete='CASCADE')
    op.drop_constraint('detail_description_nodeId_fkey', 'detail_description', type_='foreignkey')
    op.create_foreign_key(None, 'detail_description', 'node', ['nodeId'], ['id'], ondelete='CASCADE')
    op.drop_constraint('detail_instruction_nodeId_fkey', 'detail_instruction', type_='foreignkey')
    op.create_foreign_key(None, 'detail_instruction', 'node', ['nodeId'], ['id'], ondelete='CASCADE')
    op.drop_constraint('edge_targetId_fkey', 'edge', type_='foreignkey')
    op.drop_constraint('edge_sourceId_fkey', 'edge', type_='foreignkey')
    op.drop_constraint('edge_processId_fkey', 'edge', type_='foreignkey')
    op.create_foreign_key(None, 'edge', 'process', ['processId'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'edge', 'node', ['sourceId'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'edge', 'node', ['targetId'], ['id'], ondelete='CASCADE')
    op.drop_constraint('general_instruction_nodeId_fkey', 'general_instruction', type_='foreignkey')
    op.create_foreign_key(None, 'general_instruction', 'node', ['nodeId'], ['id'], ondelete='CASCADE')
    op.drop_constraint('node_processId_fkey', 'node', type_='foreignkey')
    op.create_foreign_key(None, 'node', 'process', ['processId'], ['id'], ondelete='CASCADE')
    op.drop_column('process', 'noExecutes')
    op.drop_constraint('process_doc_processId_fkey', 'process_doc', type_='foreignkey')
    op.create_foreign_key(None, 'process_doc', 'process', ['processId'], ['id'], ondelete='CASCADE')
    op.drop_constraint('split_question_nodeId_fkey', 'split_question', type_='foreignkey')
    op.create_foreign_key(None, 'split_question', 'node', ['nodeId'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'split_question', type_='foreignkey')
    op.create_foreign_key('split_question_nodeId_fkey', 'split_question', 'node', ['nodeId'], ['id'])
    op.drop_constraint(None, 'process_doc', type_='foreignkey')
    op.create_foreign_key('process_doc_processId_fkey', 'process_doc', 'process', ['processId'], ['id'])
    op.add_column('process', sa.Column('noExecutes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'node', type_='foreignkey')
    op.create_foreign_key('node_processId_fkey', 'node', 'process', ['processId'], ['id'])
    op.drop_constraint(None, 'general_instruction', type_='foreignkey')
    op.create_foreign_key('general_instruction_nodeId_fkey', 'general_instruction', 'node', ['nodeId'], ['id'])
    op.drop_constraint(None, 'edge', type_='foreignkey')
    op.drop_constraint(None, 'edge', type_='foreignkey')
    op.drop_constraint(None, 'edge', type_='foreignkey')
    op.create_foreign_key('edge_processId_fkey', 'edge', 'process', ['processId'], ['id'])
    op.create_foreign_key('edge_sourceId_fkey', 'edge', 'node', ['sourceId'], ['id'])
    op.create_foreign_key('edge_targetId_fkey', 'edge', 'node', ['targetId'], ['id'])
    op.drop_constraint(None, 'detail_instruction', type_='foreignkey')
    op.create_foreign_key('detail_instruction_nodeId_fkey', 'detail_instruction', 'node', ['nodeId'], ['id'])
    op.drop_constraint(None, 'detail_description', type_='foreignkey')
    op.create_foreign_key('detail_description_nodeId_fkey', 'detail_description', 'node', ['nodeId'], ['id'])
    op.drop_constraint(None, 'button_name', type_='foreignkey')
    op.create_foreign_key('button_name_nodeId_fkey', 'button_name', 'node', ['nodeId'], ['id'])
    # ### end Alembic commands ###
