"""test

Revision ID: 8f4123253988
Revises: ad486c67feee
Create Date: 2019-04-04 15:27:05.229246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f4123253988'
down_revision = 'ad486c67feee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('process', sa.Column('Date', sa.Integer(), nullable=True))
    op.drop_column('process', 'importDate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('process', sa.Column('importDate', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('process', 'Date')
    # ### end Alembic commands ###
