"""changes

Revision ID: ca96dbf6ee92
Revises: 0972a41c9fb0
Create Date: 2019-04-04 19:23:57.294680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca96dbf6ee92'
down_revision = '0972a41c9fb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('process_doc', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.drop_column('process_doc', 'idkujk')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('process_doc', sa.Column('idkujk', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('process_doc', 'id')
    # ### end Alembic commands ###
