"""new structure

Revision ID: eb953db824d4
Revises: 4a243c196e6f
Create Date: 2019-04-04 18:11:05.606700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb953db824d4'
down_revision = '4a243c196e6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('button_name',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('nodeId', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['nodeId'], ['node.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detail_description',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('nodeId', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['nodeId'], ['node.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('splitquestion',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('nodeId', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['nodeId'], ['node.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('edge', 'edgeText')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('edge', sa.Column('edgeText', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_table('splitquestion')
    op.drop_table('detail_description')
    op.drop_table('button_name')
    # ### end Alembic commands ###
